language: go
go:
  - "1.7"
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.11"
  - "1.12"
  - "1.13"
  - "1.14"
  - "tip"
script:
  - go build ./...
  - go get -u github.com/stretchr/testify/assert
  - go test -race -parallel 4 -timeout 30s -v ./...
